# Generated by Django 3.1.4 on 2021-01-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='chexk_in',
            new_name='check_in',
        ),
    ]
